In [1]:
from sklearn.decomposition import TruncatedSVD
from sklearn.random_projection import sparse_random_matrix
import numpy as np

In [2]:
X = sparse_random_matrix(100, 100, density=0.01, random_state=5)

In [3]:
X

<100x100 sparse matrix of type '<class 'numpy.float64'>'
	with 79 stored elements in Compressed Sparse Row format>

In [4]:
X.toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [5]:
np.where(X.toarray()!=0)

(array([ 1,  1,  3,  3,  4,  4,  5,  7,  8, 10, 10, 14, 17, 21, 21, 22, 22,
        23, 23, 23, 24, 26, 28, 28, 28, 30, 32, 32, 32, 34, 37, 38, 38, 40,
        42, 44, 44, 44, 48, 50, 52, 53, 53, 54, 55, 55, 55, 55, 56, 56, 57,
        58, 62, 64, 65, 66, 67, 73, 75, 76, 77, 77, 78, 79, 79, 80, 82, 83,
        86, 88, 89, 91, 93, 94, 96, 96, 96, 98, 99]),
 array([23, 64, 37, 62, 48, 98, 10, 54, 24, 30, 52, 66, 59, 85, 88,  8, 66,
        54, 61, 77, 36, 16, 30, 48, 66, 50, 19, 79, 96, 93, 52, 48, 88, 33,
        97, 40, 55, 57, 55, 72, 54,  5, 47, 33, 33, 56, 80, 90, 12, 34, 66,
        74, 81, 24, 45, 93, 75, 20, 75,  2, 21, 51, 85, 61, 85,  9, 28, 36,
        37, 34, 42, 13, 30,  7, 17, 20, 31,  8, 72]))

In [6]:
X.toarray()[5][10] # X.toarray()[array_1][array_2]

-1.0

In [7]:
svd = TruncatedSVD(n_components=5, n_iter=7, random_state=42)

In [11]:
svd.fit(X)

TruncatedSVD(algorithm='randomized', n_components=5, n_iter=7,
       random_state=42, tol=0.0)

In [15]:
ans = svd.transform(X)

In [16]:
svd.inverse_transform(ans)

array([[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  7.25428490e-20,   2.02558934e-19,  -3.52224689e-09, ...,
          1.01868812e-07,  -2.49447733e-04,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -8.06149103e-18,  -2.45826640e-17,   4.28128863e-06, ...,
          2.17781652e-08,   3.61522941e-03,   0.00000000e+00],
       [ -1.36420641e-20,  -6.80065957e-20,  -2.46438253e-08, ...,
         -1.06901946e-07,   9.22690898e-05,   0.00000000e+00]])

In [19]:
ans2 = svd.fit_transform(X)

In [20]:
svd.inverse_transform(ans2)

array([[ -8.18498673e-33,  -1.03463110e-32,   3.97632415e-21, ...,
          7.97763851e-21,   1.44317547e-17,   0.00000000e+00],
       [  1.47517484e-19,   3.75522171e-19,  -1.30531538e-08, ...,
          1.75882274e-07,  -5.05101008e-04,   0.00000000e+00],
       [ -2.34946865e-33,  -6.20571859e-33,   1.10761637e-21, ...,
          2.10125623e-22,   5.63410775e-18,   0.00000000e+00],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [ -8.10696576e-18,  -2.47073756e-17,   4.31163855e-06, ...,
          4.77139987e-08,   3.72240619e-03,   0.00000000e+00],
       [ -3.43467099e-20,  -1.28596537e-19,  -3.93920360e-08, ...,
         -1.82510431e-07,   1.84516569e-04,   0.00000000e+00]])

# Youtube SVD introdction
   1. [Intro](https://www.youtube.com/watch?v=P5mlg91as1c)
   2. [Example](https://www.youtube.com/watch?v=K38wVcdNuFc)


In [21]:
A = [[1,1,1,0,0],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [0,1,0,2,2]]

In [25]:
A = np.array(A)

In [27]:
A

array([[1, 1, 1, 0, 0],
       [3, 3, 3, 0, 0],
       [4, 4, 4, 0, 0],
       [5, 5, 5, 0, 0],
       [0, 2, 0, 4, 4],
       [0, 0, 0, 5, 5],
       [0, 1, 0, 2, 2]])

In [28]:
svd = TruncatedSVD(n_components=3, n_iter=7, random_state=42)

In [29]:
svd.fit(A)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7,
       random_state=42, tol=0.0)

In [30]:
svd.components_ #This is the right singular vector

array([[ 0.56225841,  0.5928599 ,  0.56225841,  0.09013354,  0.09013354],
       [-0.12664138,  0.02877058, -0.12664138,  0.69537622,  0.69537622],
       [ 0.40966748, -0.80479152,  0.40966748,  0.0912571 ,  0.0912571 ]])

In [31]:
svd.explained_variance_ratio_ 

array([ 0.45541876,  0.53055197,  0.01402927])

In [32]:
svd.explained_variance_

array([ 8.36483439,  9.74483207,  0.25768048])

In [33]:
new_V = svd.components_ [:2] #remove noise which is in row 3

In [34]:
new_V

array([[ 0.56225841,  0.5928599 ,  0.56225841,  0.09013354,  0.09013354],
       [-0.12664138,  0.02877058, -0.12664138,  0.69537622,  0.69537622]])

In [35]:
q = [5,0,0,0,0] #two query
d = [0,4,5,0,0]

In [37]:
q_ans = np.inner(q,new_V)
p_ans = np.inner(d,new_V)

In [38]:
print(q_ans)
print(p_ans)

[ 2.81129203 -0.63320691]
[ 5.18273163 -0.51812457]


In [39]:
z = [0,0,0,4,5]
z_ans = np.inner(z,new_V)

In [40]:
print(z_ans)

[ 0.81120184  6.25838598]


In [47]:
B = [[0,1,0,2,2],
    [3,3,3,0,0],
    [4,4,4,0,0],
    [5,5,5,0,0],
    [0,2,0,4,4],
    [0,0,0,5,5],
    [1,1,1,0,0]]#Exchanging rows won't make any difference

In [48]:
svd.fit(B)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7,
       random_state=42, tol=0.0)

In [49]:
new_V = svd.components_ [:2]
new_V

array([[ 0.56225841,  0.5928599 ,  0.56225841,  0.09013354,  0.09013354],
       [-0.12664138,  0.02877058, -0.12664138,  0.69537622,  0.69537622]])

In [50]:
#Exchange Column 0 with Column 4
C = [[2,1,0,2,0],
    [0,3,3,0,3],
    [0,4,4,0,4],
    [0,5,5,0,5],
    [4,2,0,4,0],
    [5,0,0,5,0],
    [0,1,1,0,1]]#type of movies must be sorted in order

In [51]:
svd.fit(C)

TruncatedSVD(algorithm='randomized', n_components=3, n_iter=7,
       random_state=42, tol=0.0)

In [52]:
new_V = svd.components_ [:2]
new_V

array([[ 0.09013354,  0.5928599 ,  0.56225841,  0.09013354,  0.56225841],
       [ 0.69537622,  0.02877058, -0.12664138,  0.69537622, -0.12664138]])

In [53]:
q_ans = np.inner(q,new_V)
p_ans = np.inner(d,new_V)

In [54]:
print(q_ans)
print(p_ans)

[ 0.45066769  3.4768811 ]
[ 5.18273163 -0.51812457]
